### ISSUE TITLE
When the container size changes, the gutterHeight is sometimes wrong

### ISSUE THREAD

**Issue by mquandalle** [wadackel/react-stack-grid#19]
Hi,

In a mobile view I have a StackGrid which can either have 1 column in portrait orientation, and 2 columns in landscape mode. I'm using size-me/component-queries as recommended in #10 and this is working well expect for the gutter height that is either too big or too small when switching between the 2 layouts.

Edit: This seems to be the case only with column widths defined with percentage strings.

**Comment by tsuyoshiwada** [comment]
Hi, Thanks for report.

It is difficult to check right away, so I think I will try it when I go home.
Please wait a moment.

**Comment by tsuyoshiwada** [comment]
I tried to check it, but I did not know how to reproduce it...
It is helpful if you can tell me the smallest code that can reproduce Issue, if possible.

**Comment by mquandalle** [comment]
Here is a minimal clonable reproduction of the issue: https://github.com/mquandalle/repro-react-stack-grid-issue-19

**Comment by tsuyoshiwada** [comment]
Thank you for the sample code!

A bug was confirmed.
It seems that there is a problem with acquiring the height of the item as you say.
I will think about how to fix it.

---

**Note:** If you are in a hurry, you can respond by changing the `key` property as follows.

```javascript
// Grid items
<div
  key={`${this.state.isLarge ? 'lg-' : 'md-'}${index}`}
  style={{
    height: this.state.isLarge ? 100 : 130,
    background: "#eee",
    border: "1px solid #333"
  }}
/>
```

**Comment by tsuyoshiwada** [comment]
Hi,
Now, I'm trying to counter Issue.

The problem is that we need to detect the height change of the grid item.

Specifically, it is to implement `ResizeObserver` in the grid item. (use polyfill)
By doing so you can recalculate the layout when the height of the grid item is changed.

However, when the number of grid items is large, it has a bad influence on performance.
That is because there are many subjects to detection.

---

How about the following API as a different solution?

```javascript
/**
 * It calls the API of the StackGrid instance
 * when the height of the grid item changes.
 */
class YourComponent extends React.Component {
  /**
   * It simulates when the height of the grid item changes.
   */
  something() {
    this.node.updateLayout();
  }

  // ...

  render() {
    return (
      <StackGrid
        onInitialized={node => this.node = node}
      >
        {/* Grid items */}
      </StackGrid>
    );
  }
}
```

> Note: This is an idea.

**Comment by tsuyoshiwada** [comment]
Hi @mquandalle.

I'm sorry I was late...
What is the situation after that?

Released version 0.3.0 which supports manual layout update.
Please check when you have time.


## Reference

* [Live Demo](https://tsuyoshiwada.github.io/react-stack-grid/#/change-size/) ([Source Code](https://github.com/tsuyoshiwada/react-stack-grid/blob/master/docs/js/pages/ChangeSize.js))
* [How to manually update layout ?](https://github.com/tsuyoshiwada/react-stack-grid#how-to-manually-update-layout-)

> **Note:** The `onInitialized` used in the proposal is renamed to` gridRef`.

**Comment by nerdess** [comment]
the issue with the gutterHeight is still persistent. i got a really simple responsive setup like so:

<StackGrid columnWidth={this.getColumnWidth()} gutterWidth={20} gutterHeight={20}>

the first time i set the gutterHeight and check my automatically updated localhost:3000 it is fine but as soon as i hit refresh the gutterHeight is much smaller, something around 5 pixel.

**Comment by tsuyoshiwada** [comment]
Hi @nerdess Thank you for report :smiley:

That's a strange phenomenon ...
It would be greatly appreciated if you could present a minimal reproducible code if possible.

**Comment by JamesBliss** [comment]
Hi, I am also having this issue. On refresh the `gutterHeight` calculates correctly but when I resize browser it looses the ability. I've tried setting `gutterHeight` to 0 and having using padding on an inner element to force space but it seems `react-stack-grid` is still not calculating correctly. 

I have using `styled-components` to style inner elements but I do not believe that should be causing any issues. 

Any help would be much appreciated.
