### ISSUE TITLE
error when rendering..

### ISSUE THREAD

**Issue by lisongx** [wadackel/react-stack-grid#55]
it's not very stable from what I check, sometimes the image will overlap and the result is not right then
<img width="1141" alt="screen shot 2018-07-17 at 12 56 31 pm" src="https://user-images.githubusercontent.com/349342/42797583-7be160ac-89c2-11e8-8321-de73d7959169.png">

if refreshed, it would be right for some chance but no always

**Comment by mnindrazaka** [comment]
Same here

**Comment by landaumd** [comment]
I think you add `monitorImagesLoaded={true}` to the stack grid like this: 
```            
<StackGrid
     duration={duration}
     columnWidth={w}
     gutterWidth={gutter}
     gutterHeight={gutter}
     easing={easing}
     monitorImagesLoaded={true}
     >
          {grid-content}
</StackGrid>
```

**Comment by lisongx** [comment]
I fix the issue by specify the img size my self...
