### ISSUE TITLE
Grid item height change delay?

### ISSUE THREAD

**Issue by samblackk** [wadackel/react-stack-grid#58]
Hello! I'm curious on how I can prevent this from happening: 
![screen recording 2018-11-16 at 01 42 pm](https://user-images.githubusercontent.com/6862485/48640792-af9d5700-e9a5-11e8-8e90-56633247060a.gif)

The layout will update it's height (and not overlap) on the second "tag" submission but not on the first one that causes the overlap. It also doesn't re-update when removing tags and the grid item returns to it's original size.
 
```
handleChange = (tags) => {
  this.setState(tags);
  return this.grid.updateLayout();
}

 <StackGrid
  columnWidth={'33%'}
  gutterWidth={10}
  gutterHeight={10}
  gridRef={(grid) => this.grid = grid}
>
  {widgets.map((widget) =>
      <TagInput
          key={widget.id}
          id={widget.id}
          name={widget.name}
          description={widget.description}
          value={this.state[widget.id] || []}
          options={{placeholder: widget.placeholder}}
          handleChange={this.handleChange}
      />
  )}
</StackGrid>
```

**Comment by samblackk** [comment]
Nevermind, it was an issue with my state. ✌️

**Comment by ntatko** [comment]
@singram26 Would you mind showing what changed in your state? I'm having the same problem, and I'd love to see what changed in your state.
