### ISSUE TITLE
Cannot access live demo link

### ISSUE THREAD

**Issue by ljhyeok** [wadackel/react-stack-grid#69]
hello!
first, I'm always grateful for your hard work.

I wannt to see live demo, but I can access [Live demo](https://tsuyoshiwada.github.io/react-stack-grid/).

Check please... I want to see the demo.

then have a nice day!

**Comment by m-jabrane** [comment]
Hi! If you are very interested to see the demo, you can just clone the project to your local machine and then run it there.

**Comment by mashirozx** [comment]
Hey guys, look here: https://wadackel.github.io/react-stack-grid/
