### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use. / Warning: componentWillReceiveProps has been renamed, and is not recommended

### ISSUE THREAD

**Issue by KANIYONIKA** [wadackel/react-stack-grid#74]
Warning: componentWillMount has been renamed, and is not recommended for use.
Warning: componentWillReceiveProps has been renamed, and is not recommended 

When I use the following code, I get the above two warnings.
Do you get them too?
I know it's a warning and I can ignore it, but I'd like to fix it if possible.
I'd appreciate any help you can give me.
```
import StackGrid from 'react-stack-grid'

export const Test = () => {
  return (
    <StackGrid columnWidth={150}>
      <div key="key1">Item 1</div>
      <div key="key2">Item 2</div>
      <div key="key3">Item 3</div>
    </StackGrid>
  )
}
```

![スクリーンショット 2021-09-07 17 25 47](https://user-images.githubusercontent.com/72968547/132311587-81f0ef95-8a9d-4a3f-9f99-4ee61c1a675d.png)

**Comment by crystal-clear-moon** [comment]
Hello, @ks-develox 
I have same issue, did you fix it? Could you tell me how to fix it?

**Comment by KANIYONIKA** [comment]
Hello :) @crystal-clear-moon 
No! I decide to use  my-masonry-grid instead of this
